module.exports = {
    // items
    
    NEW_ITEM: 'NEW_ITEM',
    
    CREATE_ITEM: 'CREATE_ITEM',
    CREATE_ITEM_REQUEST: 'CREATE_ITEM_REQUEST',
    CREATE_ITEM_RESPONSE: 'CREATE_ITEM_RESPONSE',
    CREATE_ITEM_SUCCESS: 'CREATE_ITEM_SUCCESS',
    CREATE_ITEM_FAIL: 'CREATE_ITEM_FAIL',
    
    UPDATE_ITEM: 'UPDATE_ITEM',
    UPDATE_ITEM_REQUEST: 'UPDATE_ITEM_REQUEST',
    UPDATE_ITEM_RESPONSE: 'UPDATE_ITEM_RESPONSE',
    UPDATE_ITEM_SUCCESS: 'UPDATE_ITEM_SUCCESS',
    UPDATE_ITEM_FAIL: 'UPDATE_ITEM_FAIL',
    
    DELETE_TEMP_ITEM: 'DELETE_TEMP_ITEM',
    DELETE_ITEM: 'DELETE_ITEM',
    DELETE_ITEM_REQUEST: 'DELETE_ITEM_REQUEST',
    DELETE_ITEM_RESPONSE: 'DELETE_ITEM_RESPONSE',
    DELETE_ITEM_SUCCESS: 'DELETE_ITEM_SUCCESS',
    DELETE_ITEM_FAIL: 'DELETE_ITEM_FAIL',
    
    GET_ITEM: 'GET_ITEM',
    GET_ITEM_REQUEST: 'GET_ITEM_REQUEST',
    GET_ITEM_RESPONSE: 'GET_ITEM_RESPONSE',
    GET_ITEM_SUCCESS: 'GET_ITEM_SUCCESS',
    GET_ITEM_FAIL: 'GET_ITEM_FAIL',
    
    SEARCH_ITEM: 'SEARCH_ITEM',
    SEARCH_ITEM_REQUEST: 'SEARCH_ITEM_REQUEST',
    SEARCH_ITEM_RESPONSE: 'SEARCH_ITEM_RESPONSE',
    SEARCH_ITEM_SUCCESS: 'SEARCH_ITEM_SUCCESS',
    SEARCH_ITEM_FAIL: 'SEARCH_ITEM_FAIL',
}